name: Montag 08:00 – Telegram Angebote

on:
  schedule:
    # Zwei Zeiten in UTC, damit es zu 08:00 Europe/Berlin passt – Sommer & Winterzeit:
    - cron: "0 6 * * 1"   # 06:00 UTC (Sommer -> 08:00 Berlin)
    - cron: "0 7 * * 1"   # 07:00 UTC (Winter -> 08:00 Berlin)
  workflow_dispatch: {}    # manuell auslösbar für Tests

jobs:
  send-deals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SEND_TIME: ${{ secrets.SEND_TIME }}
        run: |
          python angebote_bot.py
